---
- name: Allow unprivileged binding to port 80 (for Traefik)
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "80"
    sysctl_file: /etc/sysctl.d/90-homelab.conf
    reload: true

- name: Enable IPv6 forwarding (for homelab bridge)
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_file: /etc/sysctl.d/90-homelab.conf
    reload: true
