---
all:
  children:
    dev:
      hosts:
        laptop:
          ansible_host: localhost
          ansible_connection: local
          admin_user: "{{ lookup('env', 'USER') }}"
          pihole_host_ip: 127.0.0.1
          extra_firewall_ports: []

    prd:
      hosts:
        homeserver:
          ansible_host: 192.168.86.10     # update to real IP
          ansible_connection: ssh
          admin_user: cgrau
          pihole_host_ip: 192.168.86.10   # update to real IP
          extra_firewall_ports:
            - { port: 53,    proto: tcp }
            - { port: 53,    proto: udp }
            - { port: 1900,  proto: udp }
            - { port: 32400, proto: tcp }
            - { port: 32410, proto: udp }
            - { port: 32412, proto: udp }
            - { port: 32413, proto: udp }
            - { port: 32414, proto: udp }
            - { port: 32469, proto: tcp }
            - { port: 7359,  proto: udp }
            - { port: 8096,  proto: tcp }
