---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: solaredge
    scrape_interval: 5m
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets:
          - prometheus-exporter-solaredge:8080

  - job_name: openweather
    scrape_interval: 5m
    static_configs:
      - targets:
          - prometheus-exporter-openweather:9091
