---
- name: Install Podman Quadlets for homelab services
  hosts: all
  become: false
  vars:
    ansible_connection: community.general.machinectl
    ansible_machinectl_user: "{{ homelab_user }}"
    ansible_user: "{{ admin_user }}"
  roles:
    - quadlets
